# Site settings
name: Arshdeep's Portfolio
title: Arsh, who?
description: A technologist who thrives on finding solutions for challenges in the ever-evolving digital space â€“ writing secure code, optimizing processes & ensuring customer success with products.
url: https://arshdeepsingh.me
baseurl: ""
# destination: ./docss
email: arshdeep.singh4@pace.edu
logo: https://ar33h.github.io/assets/images/favicon.png
social:
  - title: LinkedIn
    url: https://www.linkedin.com/in/ar33h
  - title: Instagram
    url: https://instagram.com/arshdeepsengh
  - title: Dribbble
    url: https://dribbble.com/ar33h
  - title: Vimeo
    url: https://vimeo.com/ar33h
  
  
# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
